name: "Build & Publish PHP"
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: ${{ matrix.version }}-${{ matrix.type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [ '8.3' ]
        type: [ 'fpm', 'cli', 'zts' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Rename version
        id: version-rename
        run: echo "tag=$(echo ${{ matrix.version }} | tr -d '.')">> $GITHUB_OUTPUT

      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./php-${{ matrix.type }}.dockerfile
          build-args: |
            BASE_IMAGE=php:${{ matrix.version }}-${{ matrix.type }}
          push: true
          tags: ${{ secrets.DH_USERNAME }}/php:${{ matrix.type }}-${{ steps.version-rename.outputs.tag }}-latest
